// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
/// 
/// import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS3ZUNo8mHJYBw4Ush6JC0FBCSCQjGjyA',
    appId: '1:676297522863:web:42c3982e4c97dfdc351e5a',
    messagingSenderId: '676297522863',
    projectId: 'bookverse-68d8f',
    authDomain: 'bookverse-68d8f.firebaseapp.com',
    storageBucket: 'bookverse-68d8f.firebasestorage.app',
    measurementId: 'G-V89M1J80CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8p9estc5Lsk3gefF_aRaSwlT-gXf5GWU',
    appId: '1:676297522863:android:1e8e37342f284252351e5a',
    messagingSenderId: '676297522863',
    projectId: 'bookverse-68d8f',
    storageBucket: 'bookverse-68d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDk6W1_owHIdpqxVTTPYch5xUWSBhLuLo',
    appId: '1:676297522863:ios:29cbfd9040e6e679351e5a',
    messagingSenderId: '676297522863',
    projectId: 'bookverse-68d8f',
    storageBucket: 'bookverse-68d8f.firebasestorage.app',
    iosBundleId: 'com.example.bookverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDk6W1_owHIdpqxVTTPYch5xUWSBhLuLo',
    appId: '1:676297522863:ios:29cbfd9040e6e679351e5a',
    messagingSenderId: '676297522863',
    projectId: 'bookverse-68d8f',
    storageBucket: 'bookverse-68d8f.firebasestorage.app',
    iosBundleId: 'com.example.bookverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS3ZUNo8mHJYBw4Ush6JC0FBCSCQjGjyA',
    appId: '1:676297522863:web:9293c7ff2fc3f03b351e5a',
    messagingSenderId: '676297522863',
    projectId: 'bookverse-68d8f',
    authDomain: 'bookverse-68d8f.firebaseapp.com',
    storageBucket: 'bookverse-68d8f.firebasestorage.app',
    measurementId: 'G-0EBHXC3TRX',
  );
}
